version: '3'
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - 4444:4444
      - 4442:4442
      - 4443:4443
    
  python3:
    restart: always
    build: .
    container_name: 'Testpython3'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./opt:/root/opt
    depends_on:
      - selenium-hub

  chrome:
    image: selenium/node-chrome
    container_name: chrome
    depends_on:
      - selenium-hub
    environment:
      - TZ=Asia/Tokyo
      - HUB_HOST=selenium-hub
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - ./opt/chromedriver_mac_arm64:/webdriver
    links:
      - selenium-hub

